### ISSUE TITLE
Dwarf Haste is broken, and here's how to fix it

### ISSUE THREAD

**Issue by valoeghese** [lochnessdragon/OriginsPlus#14]
**Describe the bug**
Crash upon using haste on some blocks. Why? You're comparing a block against an item tag. Therefore minecraft crashes upon trying to load the tag as a block tag.

**To Reproduce**
Try break something like deepslate cobblestone

**Expected behavior**
It not to crash lol

**Additional context**
You can probably fix this by not using `minecraft:stone_tool_materials` in your apply_haste block condition

Edit: A fix for this issue is in PR #10 (the 1.17 update pr by will bl), so if you merge that you can close this issue too :)

**Comment by valoeghese** [comment]
Hopefully my time debugging this issue can help it be resolved in the mod as quickly as possible. Really great mod btw, :)

**Comment by valoeghese** [comment]
Just tested in a fork. It works :)

**Comment by valoeghese** [comment]
#10 now has a commit that will fix this issue

**Comment by lochnessdragon** [comment]
Nice! Thanks for the fix.
