### ISSUE TITLE
Dwarf Origin Crashes my Game

### ISSUE THREAD

**Issue by HyperDAsriel** [lochnessdragon/OriginsPlus#15]
Whenever I do anything that selects the dwarf origin as my origin, my game closes out and I am left at a crash report screen on my minecraft launcher.

**To Reproduce**
In-game /origin set [username] [rest of the stuff needed for dwarf origin, can't remember lol.]

**Expected behavior**
I expected the dwarf origin to load after I fixed the dwarf origin file itself (dwarf origin didn't even show up before I fixed it.)

**Screenshots**
![Screenshot (93)](https://user-images.githubusercontent.com/88693458/132067707-1593b87c-0978-4c78-a440-c1b0930752ee.png)

**Desktop (please complete the following information):**
 - Chrome

**Comment by lochnessdragon** [comment]
Fixed!
