### ISSUE TITLE
The Dwarf origin doesn't appear 

### ISSUE THREAD

**Issue by possibly-here** [lochnessdragon/OriginsPlus#16]
**Describe the bug**
The dwarf origin doesn't show up neither in the "choose" menu nor in the commands. 

**Desktop**
 - OS: Windows

**Additional context**
The only other mods I have installed are the reacquired ones (origins, pehkui, fabric API). No error shows up, every other origin works, the dwarf is just not available.

**Comment by lochnessdragon** [comment]
Fixed in 1.19.3!
