### ISSUE TITLE
Unable to choose the dwarf origin

### ISSUE THREAD

**Issue by ghost** [lochnessdragon/OriginsPlus#5]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Uzuke** [comment]
My server just skipped the dwarf origins when i want to play with my friends . I'm on Opera GX and my host is Server.pro . 
I put a screenshot
![image_2021-04-29_175552](https://user-images.githubusercontent.com/83417765/116580934-229bad80-a914-11eb-9df8-d348a1368bba.png)

**Comment by lochnessdragon** [comment]
Thanks for the log! What version of Origins are you using?

**Comment by Uzuke** [comment]
> Thanks for the log! What version of Origins are you using?

1.16.5-0.7.0

**Comment by ghost** [comment]
is there any way I could play as a dwarf?

**Comment by HyperDAsriel** [comment]
Any known fix yet?
=

**Comment by lochnessdragon** [comment]
Fixed!
